# GRID mi LOCAL mi
GRID=false
PARALLEL=false

# Allure Raporlama
ENABLE_REPORTING=true

# App Reset Y�netimi
APP_NO_RESET=false

# Maksimum session /
GRID_MAX_SESSIONS=1
GRID_MAX_TOTAL_DEVICES=2

# LOCAL Appium server
LOCAL_HUB_URL=http://127.0.0.1

# GRID Selenium Hub URL
GRID_HUB_URL=http://10.4.112.22:4444

# Node'lar?n baslayacak ilk port (her node icin +1 artar)
GRID_START_NODE_PORT=1488
APPIUM_BASE_PORT=4725

# iOS
IOS_APP_PATH=src/test/resources/apps/ios/HalkKatilimMobil.app
IOS_BUNDLE_ID=test.halkkatilim.mobilebanking

# Android
ANDROID_APP_PATH=src/test/resources/apps/android/HalkKatilimMobil.apk
APP_PACKAGE=com.halkbank.mobil.dev
