# ========================================
# Cucumber Configuration
# ========================================

# Glue code (step definitions and hooks)
cucumber.glue=org.halkKatilim.stepDefs,org.halkKatilim.hooks

cucumber.plugin=pretty,html:target/reports/cucumber-report.html,json:target/reports/cucumber-report.json

cucumber.execution.parallel.enabled=false

# Execution mode (if parallel is enabled)
# cucumber.execution.parallel.mode=scenarios

# Publish to Cucumber Cloud (optional, set to true to enable)
cucumber.publish.enabled=false
cucumber.publish.quiet=true
